### ISSUE TITLE
'Use' command sometimes generate script with empty path to werf binary

### ISSUE THREAD

**Issue by diafour** [flant/multiwerf#28]
Sometimes `use` command generate a script without path to `werf` binary. No warnings, no errors, multiwerf output looks good, but script is not valid:

```
multiwerf is /home/gitlab-runner/bin/multiwerf
werf 1.0/beta stays at v1.0.1-beta.9
```

```bash
werf () 
{ 
    if [[ $1 == "--path" ]]; then
        echo '';  # <-- path to werf binary should be here
        return;
    fi;
    "$@"  # <-- path to werf binary should be here
}
```

**Comment by diafour** [comment]
PR #27 adds an error message about empty path and multiwerf will stop on this condition.

Please report here if you are faced with this problem.

**Comment by StreSSt** [comment]
I get that error sometimes.
task runned: 30 may 2019 at 11:00 MSK

```
gitlab-runner@test-runner:~$ multiwerf version
multiwerf v1.0.13
gitlab-runner@test-runner:~$ ls -al ~/bin/multiwerf 
-rwxr-xr-x 1 gitlab-runner gitlab-runner 5889664 May 27 18:48 /home/gitlab-runner/bin/multiwerf
```
I can post  new message in this tread always i get error by version multiwerf
