### ISSUE TITLE
get.sh failed to verify sha256sum

### ISSUE THREAD

**Issue by mfominov** [flant/multiwerf#34]
Checking hash sum...
get.sh: line 121: sha256sum: command not found

which sha256sum
sha256sum not found

**Comment by diafour** [comment]
Please, install this uitlity with package manager of your OS.

p.s. Most linux distributions like ubuntu, centos, alpine have this utility pre installed.

**Comment by mfominov** [comment]
problem appeared on macOS.

**Comment by lionskape** [comment]
Looks like I have a similar issue today.
But I don't remember if I has compare sum error, or I has no package error.

I used macos too.

**Comment by lionskape** [comment]
I made some hotfix for that:
https://github.com/flant/multiwerf/pull/37

**Comment by diafour** [comment]
Thank you @lionskape and @mfominov
PRs #37 and #38 are fixed this issue.
