### ISSUE TITLE
Implement garbage collection of old werf binaries

### ISSUE THREAD

**Issue by distorhead** [flant/multiwerf#41]
As a build-host admin I want to keep `~/.multiwerf` folder from growing in size by werf-binaries auto updates. Multiwerf should have a GC procedure, which should be initiated automatically and clear `~/.multiwerf` from old werf binaries.

**Comment by alexey-igrychev** [comment]
https://github.com/flant/multiwerf/pull/86
https://github.com/flant/multiwerf/pull/87
