### ISSUE TITLE
Flag to override a path to werf binary for development purposes

### ISSUE THREAD

**Issue by diafour** [flant/multiwerf#42]
scenario:

CI configuration have this command:
```
source <(multiwerf use 1.0 beta)
```

We have werf binary build from developer branch in /tmp/werf. We want that CI process uses this binary and put messages about used binary in logs.

So, we edit CI configuration:
```
source <(multiwerf use 1.0 beta --werf-path=/tmp/werf)
```

It is desired that multiwerf output clearly state that some external binary is used and that this flag should be used only for development purposes.

**Comment by alexey-igrychev** [comment]
https://github.com/flant/multiwerf/pull/53
